- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  roles:
    - { role: package, package_name: ntp, package_state: latest }
    - { role: package, package_name: re6st-node, package_state: latest }
    - { role: package, package_name: slapos-node, package_state: latest }

